version: "3.8"

services:

    web:   
        image: zdravkov/img-web
        container_name: web
        ports:

            - 80:80

        networks:

            - appnet

        depends_on:

            - db

    db:
        image: zdravkov/img-db
        container_name: db
        networks:

            - appnet
