version: "3.8"

services:

    web:   
        image: zdravkov/img-web
        container_name: web
        ports:

            - 80:80
        depends_on:

            - db    

    db:
        image: zdravkov/img-db
        container_name: db
        environment:

            MYSQL_ROOT_PASSWORD: "12345"
        
