version: "3.8"

services:

    web:   
        image: zdravkov/img-web
        container_name: web
        ports:

            - 80:80

       

        

    db:
        image: zdravkov/img-db
        container_name: db
        
